### ISSUE TITLE
Setup automated releases to PyPI

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/socksio#10]
I'm thinking using CalVer because our API isn't going to change and the only time this library will change is if there are bug-fixes.

**Comment by yeraydiazdiaz** [comment]
Wouldn't that be an argument to use SemVer? I can easily see `socksio` hitting a 1.0.0 and having only minor releases from then on.

I kinda only see CalVer to be useful for time-sensitive projects like `pip` or `pytz`.

**Comment by sethmlarson** [comment]
That's true, let's stick with semver.
