### ISSUE TITLE
Add SOCKS5 GSSAPI handshake 

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/socksio#16]

**Comment by yeraydiazdiaz** [comment]
Is https://tools.ietf.org/html/rfc2743 the right RFC for this?

**Comment by sethmlarson** [comment]
This is the right RFC for us: https://tools.ietf.org/html/rfc1961
Thankful we don't have to implement GSS :)

**Comment by yeraydiazdiaz** [comment]
I'm confused about the section about the [message protection section](https://tools.ietf.org/html/rfc1961#page-7).

Does that mean each message sent to the SOCKS server needs to be encapsulated by the GSSAPI implementation? That would force us to add an "encapsulation layer" to wrap the user's request only for GSSAPI.

**Comment by sethmlarson** [comment]
Hmmm, I need to read up on GSSAPI more, maybe it's a good idea if we put this feature last since I don't think it's used a lot in practice anymore. Most usage I've seen has been username/password. :)

**Comment by yeraydiazdiaz** [comment]
Having a look at `PySocks` seems they don't handle GSSAPI either, only no auth and username/password.

https://github.com/Anorov/PySocks/blob/master/socks.py#L456-L465

**Comment by sethmlarson** [comment]
Then we probably don't need to support it either unless someone with a need comes along. :)
