### ISSUE TITLE
Add support for SOCKS5 state machine

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/socksio#3]
We shouldn't be able to make requests before we're authenticated successfully.

**Comment by yeraydiazdiaz** [comment]
I came across https://github.com/glyph/automat some time ago, would it be a good fit?

It might be overkill if the state machine is simple though since [h11 implemented its own](https://github.com/python-hyper/h11/blob/647939a1b3ecafc19958a3147a876e66d48879eb/h11/_state.py).

**Comment by sethmlarson** [comment]
Eh, let's implement our own state machine, I think there's only a few states for TCP:

```
CLIENT_AUTH_REQUIRED
SERVER_AUTH_REPLY
CLIENT_AUTHENTICATED
TUNNEL_READY
```

Let's keep the states identical for SOCKS4 and SOCKS5 cuz 4 doesn't really have a state machine. :)

We'll have to figure out how to handle SOCKS5 UDP for HTTP/3.

**Comment by yeraydiazdiaz** [comment]
I believe this is covered now?

> We'll have to figure out how to handle SOCKS5 UDP for HTTP/3.

UDP is addressed separately in https://github.com/sethmlarson/socksio/issues/4

**Comment by sethmlarson** [comment]
Forgot to close this!
