### ISSUE TITLE
Encapsulate actions in classes?

### ISSUE THREAD

**Issue by yeraydiazdiaz** [sethmlarson/socksio#33]
While writing the examples I noticed a couple of moments where it felt the API was a bit too low level, for example:

`conn.request(socks4.SOCKS4Command.CONNECT, "216.58.204.78", 80)`

I noticed `h11`'s API [encapsulates these actions in classes](https://h11.readthedocs.io/en/latest/api.html#h11.Request) and reduces the [`Connection` class's API](https://h11.readthedocs.io/en/latest/api.html#h11.Connection) to just methods that deal with sending, recieving and state control.

Of course, there's quite a difference in complexity between the protocols, but I think it might be worth taking a page from their book in that regard, particularly for SOCKS5 where there's a few more actions that can be performed.

Thoughts?

**Comment by sethmlarson** [comment]
I think aligning with something `h11` is doing is always a good idea, let's do it!
