### ISSUE TITLE
Acceptance tests

### ISSUE THREAD

**Issue by yeraydiazdiaz** [sethmlarson/socksio#38]
Up until now I've been running the example scripts against a local SSH proxy, it would be nice to have this process automated.

I believe the SSH proxy does not support username/password though, [mitmproxy](https://mitmproxy.org/) would've been excellent but it only supports SOCKS5.

I'm trying out [Dante](https://www.inet.no/dante/index.html) which seems pretty full featured. 

Any other suggestions?

**Comment by sethmlarson** [comment]
Yeah it'd be nice if we could run acceptance tests as a part of our CI to make sure our example scripts don't break. I actually haven't used a SOCKS server before so I don't have any additional suggestions. :)
