### ISSUE TITLE
Difference with socks5?

### ISSUE THREAD

**Issue by yeraydiazdiaz** [sethmlarson/socksio#40]
I just found https://github.com/mike820324/socks5/ via https://github.com/python-trio/hip/issues/77. It looks exactly like what we're doing in `socksio`?

**Comment by sethmlarson** [comment]
They have a bunch of dependencies for no benefit, that was the core reason to start socksio.

**Comment by yeraydiazdiaz** [comment]
Fair enough, I thought there were no sansio libraries _at all_ so I thought I'd ask. 👍
