### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yeraydiazdiaz** [sethmlarson/socksio#44]
I think it'd be good to start making a proper documentation, ideally with API documentation.

I was thinking of (surprise) [copying h11's format](https://github.com/python-hyper/h11/blob/master/h11/_connection.py#L113-L124).

Thoughts?

**Comment by sethmlarson** [comment]
Definitely need documentation, I can setup RTD and attach it to the repository. You're thinking of using autosphinx? :)

**Comment by yeraydiazdiaz** [comment]
I didn't know there was such a thing 😄
