### ISSUE TITLE
Is there an example to proxy https traffic?

### ISSUE THREAD

**Issue by Congee** [sethmlarson/socksio#49]
Thank you for this cool library. I'm trying to get socksio and httpx work.
changing the port from 80 to 443 leads me to `b'\x05\x00\x00\x01\xac\x12\x00\x02\xe8\x0c'` and empty response b'' afterwards.
https://github.com/sethmlarson/socksio/blob/ff666fed4cd566d4196d9da67ade88ff21017514/examples/example_socks5.py#L48

Any advice? 🤔

**Comment by sethmlarson** [comment]
I'm assuming you're trying to do the following:

[ Your Program ] ---> [ SOCKS proxy ] ---> [ HTTPS Server ]

In this case you'd talk to the SOCKS proxy and ask for a connection to ("google.com", 443), wait for a successful reply from your SOCKS proxy and then start the TLS handshake on the now tunneled TCP socket. This sounds more like an HTTPX question / issue potentially?

**Comment by Congee** [comment]
yeah, I've trying to get socksio work with httpcore. Thank you!
