### ISSUE TITLE
Existing usage in the wild?

### ISSUE THREAD

**Issue by florimondmanca** [sethmlarson/socksio#50]
Hi people :-)

Just a small question from me. I'm eager to bootstrap SOCKS support in HTTPX/HTTPCore back up from previous work (@yeraydiazdiaz's https://github.com/encode/httpcore/pull/51, also https://github.com/encode/httpcore/pull/187).

I _thought_ URLLib3 had migrated its SOCKS support to use `socksio`, but looking at the GitHub repo there I'm not able to find a reference to `socksio` anymore.

Is this package depended upon by a project yet? I'm happy to lend a hand with maintenance if we integrate this into HTTPCore. Just curious what the status is.

**Comment by sethmlarson** [comment]
This project isn't a dependency of urllib3 or any project I believe. urllib3 likely won't switch unless async support is added. I'm fine with whatever direction you think is best for the project, I consider it mostly complete for the cases of proxying HTTP requests.
