### ISSUE TITLE
dead code path

### ISSUE THREAD

**Issue by clandestinenetworks** [sethmlarson/socksio#51]
????? 
https://github.com/sethmlarson/socksio/blob/master/socksio/socks5.py#L332

**Comment by clandestinenetworks** [comment]
dude PLEASE just take this down and pull it from PyPI if it can't work ...

**Comment by clandestinenetworks** [comment]
`In [87]: conn.send((socks5.SOCKS5AuthMethod.NO_AUTH_REQUIRED, req))`

**Comment by sethmlarson** [comment]
We're using [`functools.singeldispatchmethod`](https://docs.python.org/3/library/functools.html#functools.singledispatchmethod) which should use `raise NotImplementedError` for the default case.
